modLoader="javafml"
loaderVersion="${neoforge_loader_version_range}"
license="MIT"

[[mods]]
modId="cascade"
version="${version}"
displayName="Cascade"
authors="ChocoBoy"
description="A visual effects and sequencing library for NeoForge."

[[dependencies.cascade]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.cascade]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
